# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 249)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnGeraMega = QtWidgets.QPushButton(self.centralwidget)
        self.btnGeraMega.setGeometry(QtCore.QRect(10, 20, 131, 33))
        self.btnGeraMega.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btnGeraMega.setFont(font)
        self.btnGeraMega.setObjectName("btnGeraMega")
        self.btnGeraFacil = QtWidgets.QPushButton(self.centralwidget)
        self.btnGeraFacil.setGeometry(QtCore.QRect(10, 120, 131, 33))
        self.btnGeraFacil.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btnGeraFacil.setFont(font)
        self.btnGeraFacil.setObjectName("btnGeraFacil")
        self.labelRetornoFacil = QtWidgets.QLabel(self.centralwidget)
        self.labelRetornoFacil.setGeometry(QtCore.QRect(10, 170, 741, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.labelRetornoFacil.setFont(font)
        self.labelRetornoFacil.setStyleSheet("color: blue;")
        self.labelRetornoFacil.setText("")
        self.labelRetornoFacil.setObjectName("labelRetornoFacil")
        self.labelRetornoMega = QtWidgets.QLabel(self.centralwidget)
        self.labelRetornoMega.setGeometry(QtCore.QRect(10, 70, 741, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.labelRetornoMega.setFont(font)
        self.labelRetornoMega.setStyleSheet("color: blue;")
        self.labelRetornoMega.setText("")
        self.labelRetornoMega.setObjectName("labelRetornoMega")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gerador de números"))
        self.btnGeraMega.setText(_translate("MainWindow", "Mega-sena:"))
        self.btnGeraFacil.setText(_translate("MainWindow", "Lotofácil:"))
